repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.12.7
  hooks:
    # Run the linter.
    - id: ruff-check
    # Run the formatter.
    - id: ruff-format

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
    -   id: check-docstring-first
    -   id: check-merge-conflict
    -   id: check-added-large-files
    -   id: name-tests-test

- repo: https://github.com/RobertCraigie/pyright-python
  rev: v1.1.403
  hooks:
  - id: pyright

- repo: https://github.com/PyCQA/docformatter
  rev: v1.7.7
  hooks:
    - id: docformatter
      description: 'Formats docstrings to follow PEP 257.'
      args: [-i]
      language: python
      types: [python]
